"""
Logging Configuration
"""

logging:
    version: 1
    formatters:
        Pipelineusingpolars:
            format: "Pipeline Using Polars - %(asctime)s -%(levelname)s - %(message)s"
    handlers:
        console: 
            class: logging.StreamHandler
            formatter: Pipelineusingpolars
            level: DEBUG
    root:
        level: DEBUG
        handlers: [console]